version: '3.1'
services:
  web:
    ports:
      - "3000:3000"
    build:
      context: .
      dockerfile: Dockerfile

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - web
